query GetNftByID($zoraId: ID!) {
  media(id: $zoraId) {
    id
    creator {
      id
    }
    contentURI
    contentHash
    metadataURI
    metadataHash
    owner {
      id
    }
    prevOwner {
      id
    }
    creatorBidShare
    ownerBidShare
    prevOwnerBidShare
    createdAtBlockNumber
    createdAtTimestamp
    reserveAuctions {
      id
      approved
      approvedBlockNumber
      approvedTimestamp
      createdAtBlockNumber
      auctionCurrency {
        id
        name
        symbol
      }
      createdAtTimestamp
      curator {
        id
      }
      curatorFeePercentage
      currentBid {
        id
        amount
        bidType
        bidder {
          id
        }
        createdAtTimestamp
      }
      duration
      expectedEndTimestamp
      finalizedAtBlockNumber
      finalizedAtTimestamp
      firstBidTime
      reservePrice
      status
      tokenContract
      tokenId
      tokenOwner {
        id
      }
      previousBids(orderBy: createdAtTimestamp, orderDirection: asc) {
        id
        amount
        bidType
        bidder {
          id
        }
        createdAtTimestamp
        bidInactivatedAtTimestamp
      }
    }
  }
}
